version: "3.5"

services: 
  client: 
    container_name: activity-tracker-client
    restart: always
    build: .
    volumes:
      - './client:/usr/src/app/client'
      - '/client/node_modules'
    ports: 
      - '3000:3000'
    environment:
      - NODE_ENV=development