FROM node:10 as build

WORKDIR /usr/src/app/client

COPY client/package.json .
COPY client/yarn.lock .

RUN yarn

COPY client .

RUN yarn build



FROM nginx:stable-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

WORKDIR /usr/share/nginx/html
COPY --from=build /usr/src/app/client/build .