version: "3"

services: 
  app:
    container_name: activity-tracker-node
    restart: always
    build: .
    ports: 
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: activity-tracker-mongo
    image: mongo
    ports: 
      - '27017:27017'
