version: "3.5"

services: 
  client: 
    container_name: activity-tracker-client
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile-production
    ports: 
      - '80:80'
    environment:
      - NODE_ENV=production